name       : redis
version    : 3.2.5
release    : 1
source     :
    - http://download.redis.io/releases/redis-3.2.5.tar.gz : 8509ceb1efd849d6b2346a72a8e926b5a4f6ed3cc7c3cd8d9f36b2e9ba085315
license    : BSD-3-Clause
component  : database
summary    : Redis is an open source (BSD licensed), in-memory data structure store.
description: |
    Redis is an open source (BSD licensed), in-memory data structure store, used as database, cache and message broker. It supports data structures such as strings, hashes, lists, sets, sorted sets with range queries, bitmaps, hyperloglogs and geospatial indexes with radius queries. Redis has built-in replication, Lua scripting, LRU eviction, transactions and different levels of on-disk persistence, and provides high availability via Redis Sentinel and automatic partitioning with Redis Cluster.
build      : |
    %make
install    : |
    %make_install PREFIX=$installdir/usr
