name       : redis
version    : 7.0.11
release    : 27
source     :
    - https://github.com/redis/redis/archive/7.0.11.tar.gz : 7f1941bfa7fa01e2fd167771ff22b8e46b1a6bb0707f01b3e6308d9770e44bf3
license    : BSD-3-Clause
component  : database
summary    : Redis is an open source (BSD licensed), in-memory data structure store.
description: |
    Redis is an open source (BSD licensed), in-memory data structure store, used as database, cache and message broker. It supports data structures such as strings, hashes, lists, sets, sorted sets with range queries, bitmaps, hyperloglogs and geospatial indexes with radius queries. Redis has built-in replication, Lua scripting, LRU eviction, transactions and different levels of on-disk persistence, and provides high availability via Redis Sentinel and automatic partitioning with Redis Cluster.
builddeps  :
    - pkgconfig(tcl)
build      : |
    %make
install    : |
    %make_install PREFIX=$installdir/usr
check      : |
    %make test
