name       : redis
version    : 6.0.9
release    : 20
source     :
    - https://download.redis.io/releases/redis-6.0.9.tar.gz : dc2bdcf81c620e9f09cfd12e85d3bc631c897b2db7a55218fd8a65eaa37f86dd
license    : BSD-3-Clause
component  : database
summary    : Redis is an open source (BSD licensed), in-memory data structure store.
description: |
    Redis is an open source (BSD licensed), in-memory data structure store, used as database, cache and message broker. It supports data structures such as strings, hashes, lists, sets, sorted sets with range queries, bitmaps, hyperloglogs and geospatial indexes with radius queries. Redis has built-in replication, Lua scripting, LRU eviction, transactions and different levels of on-disk persistence, and provides high availability via Redis Sentinel and automatic partitioning with Redis Cluster.
builddeps  :
    - pkgconfig(tcl)
build      : |
    %make
install    : |
    %make_install PREFIX=$installdir/usr
check      : |
    %make test
