name       : redis
version    : 5.0.3
release    : 16
source     :
    - https://github.com/antirez/redis/archive/5.0.3.tar.gz : 7084e8bd9e5dedf2dbb2a1e1d862d0c46e66cc0872654bdc677f4470d28d84c5
license    : BSD-3-Clause
component  : database
summary    : Redis is an open source (BSD licensed), in-memory data structure store.
description: |
    Redis is an open source (BSD licensed), in-memory data structure store, used as database, cache and message broker. It supports data structures such as strings, hashes, lists, sets, sorted sets with range queries, bitmaps, hyperloglogs and geospatial indexes with radius queries. Redis has built-in replication, Lua scripting, LRU eviction, transactions and different levels of on-disk persistence, and provides high availability via Redis Sentinel and automatic partitioning with Redis Cluster.
builddeps  :
    - pkgconfig(tcl)
build      : |
    %make
install    : |
    %make_install PREFIX=$installdir/usr
check      : |
    %make test
