name       : redis
version    : 6.2.5
release    : 24
source     :
    - https://download.redis.io/releases/redis-6.2.5.tar.gz : 4b9a75709a1b74b3785e20a6c158cab94cf52298aa381eea947a678a60d551ae
license    : BSD-3-Clause
component  : database
summary    : Redis is an open source (BSD licensed), in-memory data structure store.
description: |
    Redis is an open source (BSD licensed), in-memory data structure store, used as database, cache and message broker. It supports data structures such as strings, hashes, lists, sets, sorted sets with range queries, bitmaps, hyperloglogs and geospatial indexes with radius queries. Redis has built-in replication, Lua scripting, LRU eviction, transactions and different levels of on-disk persistence, and provides high availability via Redis Sentinel and automatic partitioning with Redis Cluster.
builddeps  :
    - pkgconfig(tcl)
build      : |
    %make
install    : |
    %make_install PREFIX=$installdir/usr
check      : |
    %make test
